PRESETS = {
    "pixelpro-square": {
        "label": "PixelPro Square",
        "width": 1024,
        "height": 1024,
        "background": "#FFFFFF",
        "background_style": "solid",
        "product_scale": 0.75,
        "padding": 0.15,
        "output_format": "JPEG",
        "quality": 92,
    },
    "amazon-main": {
        "label": "Amazon Main — starting point",
        "width": 2000,
        "height": 2000,
        "background": "#FFFFFF",
        "background_style": "solid",
        "product_scale": 0.85,
        "padding": 0.075,
        "output_format": "JPEG",
        "quality": 95,
    },
    "shopify-square": {
        "label": "Shopify Square",
        "width": 2048,
        "height": 2048,
        "background": "#FFFFFF",
        "background_style": "solid",
        "product_scale": 0.80,
        "padding": 0.10,
        "output_format": "WEBP",
        "quality": 92,
    },
    "etsy-square": {
        "label": "Etsy Square — starting point",
        "width": 2000,
        "height": 2000,
        "background": "#FFFFFF",
        "background_style": "solid",
        "product_scale": 0.82,
        "padding": 0.09,
        "output_format": "JPEG",
        "quality": 92,
    },
    "ebay-square": {
        "label": "eBay Square — starting point",
        "width": 1600,
        "height": 1600,
        "background": "#FFFFFF",
        "background_style": "solid",
        "product_scale": 0.82,
        "padding": 0.09,
        "output_format": "JPEG",
        "quality": 92,
    },
    "walmart-square": {
        "label": "Walmart Square — starting point",
        "width": 2000,
        "height": 2000,
        "background": "#FFFFFF",
        "background_style": "solid",
        "product_scale": 0.82,
        "padding": 0.09,
        "output_format": "JPEG",
        "quality": 94,
    },
    "social-square": {
        "label": "Social 1:1",
        "width": 1080,
        "height": 1080,
        "background": "#FFFFFF",
        "background_style": "studio",
        "product_scale": 0.78,
        "padding": 0.11,
        "output_format": "JPEG",
        "quality": 92,
    },
    "social-portrait": {
        "label": "Social 4:5",
        "width": 1080,
        "height": 1350,
        "background": "#FFFFFF",
        "background_style": "studio",
        "product_scale": 0.78,
        "padding": 0.11,
        "output_format": "JPEG",
        "quality": 92,
    },
}

# Marketplace requirements change. These are editable production starting points, not compliance guarantees.
